homeassistant:
  customize: 
    switch.en_ngu:
      #assumed_state: false
      icon: mdi:lightbulb-on
      emulated_hue_name: "bed room light"
    
    switch.phong_khach:
      emulated_hue_name: "Living light"

  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 21.0333
  longitude: 105.85
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Ho_Chi_Minh



# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# alexa

emulated_hue:
  type: alexa
  host_ip: 192.168.1.105
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - switch

xiaomi:
  gateways:
   - mac:
     key: km8c6cspbsqc24ti

# Weather Prediction
sensor 2:
  platform: yr

sensor sen1:
  platform: random
  entity_id: sen1





switch 1:
  entity_id: congtac
  platform: broadlink
  host: 192.168.1.131
  mac: '34:EA:34:E7:E1:91'
  timeout: 15
  switches:
# Will work on most Phillips tvs:
    bedrom_light:
      friendly_name: "Đèn ngủ"
      command_on: '6RRGAN8JCRYWCQkWFgkJFgkWCRYJFhYJFgkWCRYJFgkJFgkWCRYJFgkWCRYWCQkWCRYJFgkWFgkJ
FgkWCRYWCRYJCRYJFgkAAUg='
      command_off: '6RRGAN8JFgkWCQkWFgkJFhYJFgkWCQkWCRYJFhYJFgkWCQkWCRYWCRYJFgkJFhYJFgkJFhYJCRYW
CQkWFgkWCQkWFgkWCQkAAUg='

    stair_light:
      friendly_name: "Tầng Lửng Ngoài"
      command_on: '6RRGAN8JCRYWCQkWFgkJFgkWCRYJFhYJFgkWCRYJFgkJFgkWCRYJFgkWCRYWCQkWCRYJFgkWFgkJ
FgkWCRYWCRYJCRYJFgkAAUg='
      command_off: '6RRGAN8JFgkWCQkWFgkJFhYJFgkWCQkWCRYJFhYJFgkWCQkWCRYWCRYJFgkJFhYJFgkJFhYJCRYW
CQkWFgkWCQkWFgkWCQkAAUg='

    stair_light_1:
      friendly_name: "Tầng Lửng Trong"
      command_on: '6RRGAN8JCRYWCQkWCRYJFhYJFgkJFgkWFgkJFhYJCRYJFgkWFgkWCQkWCRYJFgkWFgkJFgkWFgkJ
FhYJFgkJFgkWCRYJFgkAAUg='
      command_off: '6RRGAN8JCRYJFgkWCRYJFhYJFgkWCRYJCRYWCRYJFgkWCQkWCRYWCQkWCRYWCQkWFgkWCRYJCRYW
CRYJCRYJFgkWCRYJFgkAAUg='

    living_light_1:
      friendly_name: "Phòng khách"
      command_on: '6RRGAN8JCRYWCRYJCRYJFhYJCRYJFhYJFgkWCRYJFgkWCQkWFgkJFhYJCRYWCRYJCRYWCQkWFgkW
CRYJFgkWCRYJCRYJFgkAAUg='
      command_off: '6RRGAN8JFgkWCRYJFgkJFhYJFgkWCRYJFgkWCRYJCRYWCRYJCRYWCRYJFgkJFhYJCRYJFgkWFgkJ
FhYJCRYWCRYJFgkJFgkAAUg='

    living_light_2:
      friendly_name: "Đèn hắt phòng khách"
      command_on: '6RRGAN8JFgkWCQkWFgkJFgkWCRYJFhYJFgkWCQkWCRYJFgkWFgkJFgkWFgkWCRYJCRYJFgkWCRYW
CRYJFgkJFhYJCRYWCQkAAUg='
      command_off: '6RRGAN8JFgkJFhYJFgkJFgkWFgkJFhYJCRYWCQkWFgkWCQkWCRYWCQkWFgkWCQkWFgkWCQkWFgkW
CRYJFgkJFhYJFgkWCQkAAUg='
      


# Will work on most LG tvs
    tv_lg:
      friendly_name: "LG Tv Power"
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='

    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG Tv HDMI12"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
      
    tv_lg_hdmi3:
      friendly_name: "LG Tv HDMI3"
      command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='

    tv_lg_av1_av2:
      friendly_name: "LG Tv AV12"
      command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
      command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='

# Text to speech
tts:
  platform: google
  language: 'vi'

media_player:
  platform: vlc
  name: speaker_1

automation:
  - alias: 'Rule 1 Light on in the evening'
    trigger:
      platform: state
      entity_id: switch.en_ngu
      from: 'off'
      to: 'on'
    action:
      service: tts.google_say
      data:
        entity_id: media_player.speaker_1
        message: đèn ngủ đã bật

  - alias: 'Rule 2 Light on in the evening'
    trigger:
      platform: state
      entity_id: switch.en_ngu
      from: 'on'
      to: 'off'
    action:
      service: tts.google_say
      data:
        entity_id: media_player.speaker_1
        message: đèn ngủ đã tắt
script: !include_dir_named scripts

group: !include groups.yaml
